AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  logbook-app

  Sample SAM Template for logbook-app

Globals:
  Function:
    Timeout: 3

Resources:
  AccountHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: account/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        Account:
          Type: Api
          Properties:
            Path: /account
            Method: post

Outputs:
  AccountApi:
    Description: "API Gateway endpoint URL for Prod stage for Account Handler function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/account/"
  AccountHandlerFunction:
    Description: "Account Handler Lambda Function ARN"
    Value: !GetAtt AccountHandlerFunction.Arn
  AccountHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for Account Handler function"
    Value: !GetAtt HAccountHandlerFunctionRole.Arn
