version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::376949755107:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-Z4BMCEXLJ41T"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::376949755107:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-16OZ73NM855ID"
cloudformation_execution_role = "arn:aws:iam::376949755107:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1WGED6IENHL4"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-uapdj48ac4s6"
image_repository = ""
region = "eu-west-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::376949755107:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-QUF9BARIM8GP"
cloudformation_execution_role = "arn:aws:iam::376949755107:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-176F16MW0I3JM"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-146ptawh45p6x"
image_repository = ""
region = "eu-west-1"
